src/main/java/shop/project/pathorderserver/store/Store.java
src/main/java/shop/project/pathorderserver/user/User.java

- User
status 디폴트 어노테이션 추가
```
@ColumnDefault("true")
private boolean status; // 계정 상태 (0 : 비활성, 1 : 활성)
```
- Store
status 디폴트 어노테이션 추가
```
@ColumnDefault("true")
private boolean status; // 계정 상태 (0 : 비활성, 1 : 활성)
```
- Store
위도경도 nullable 추가
```
@Column(nullable = true)
private double latitude; // 주소 좌표 위도
@Column(nullable = true)
private double longitude; // 주소 좌표 경도
```
- Store
개점,폐점 시간 TimeStamp→String
```
private String openingTime; // 개점 시간
private String closingTime; // 폐점 시간
```

docs: User, Store

---

src/main/java/shop/project/pathorderserver/user/UserController.java
src/main/java/shop/project/pathorderserver/user/UserRequest.java
src/main/java/shop/project/pathorderserver/user/UserResponse.java
src/main/java/shop/project/pathorderserver/user/UserService.java

docs: cont,dto,serv

---

src/main/java/shop/project/pathorderserver/store/Store.java
src/main/java/shop/project/pathorderserver/store/StoreController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/db/data.sql
src/test/java/shop/project/pathorderserver/store/StoreServiceTest.java

✔️매장 디테일보기
🐯StoreController
🐯StoreService
🐯StoreResponse
🐯StoreServiceTest
⚒️Store.java
🐯엔티티 필드명 변경(imgSrc -> filePath)
⚒️data.sql
🐯store_tb INSERT 컬럼명 변경(img_src -> file_path)

feat: 매장 디테일보기 (fix: Store 엔티티, 더미 데이터 수정)

---

src/main/java/shop/project/pathorderserver/store/StoreController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java

✔️매장 디테일보기
🐯StoreController
🐯StoreService
🐯StoreResponse

feat: 사업자 정보 보기

---

src/main/java/shop/project/pathorderserver/menu/MenuRepository.java
src/main/java/shop/project/pathorderserver/order/Order.java
src/main/java/shop/project/pathorderserver/order/OrderController.java
src/main/java/shop/project/pathorderserver/order/OrderRepository.java
src/main/java/shop/project/pathorderserver/order/OrderResponse.java
src/main/java/shop/project/pathorderserver/order/OrderService.java
src/main/resources/db/data.sql
src/test/java/shop/project/pathorderserver/order/OrderRepositoryTest.java

일단 응답은 다 되니까 머지했다가 후에 다시 추가할게요

feat: 옵션수정, 주문목록보기(나중에 깔끔히 리팩토링해야함), 주문상세보기(메뉴리스트 추가해야함)

---

src/main/java/shop/project/pathorderserver/order/OrderMenu.java
src/main/java/shop/project/pathorderserver/order/OrderService.java
src/main/java/shop/project/pathorderserver/user/UserRequest.java
src/main/java/shop/project/pathorderserver/user/UserResponse.java
src/main/resources/db/data.sql

feat: order + qty +totalPrice (refactor: respDTO)

---

src/main/java/shop/project/pathorderserver/menu/MenuOption.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreRequest.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/templates/layout/sidebar.mustache
src/main/resources/templates/menus.mustache
src/main/resources/templates/orders-list.mustache
src/main/resources/templates/orders.mustache
src/main/resources/templates/store-update-form.mustache
src/main/resources/templates/store.mustache
src/test/java/shop/project/pathorderserver/store/StoreServiceTest.java
upload/spring.log

feat: createMenuOption, updateMenuOption (test: jUnit)

---

src/main/java/shop/project/pathorderserver/menu/Menu.java
src/main/java/shop/project/pathorderserver/order/OrderStatus.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/templates/layout/sidebar.mustache
src/main/resources/templates/orders.mustache

- sidebar css 동적 변화 비활성화
- 메서드 이름 및, 변수 이름 수정
- 주문 업데이트시 조리완료 추가

chore: code style, sideBar css js 비활성화 (feat: 주문 업데이트 +조리완료)

---

src/main/java/shop/project/pathorderserver/_core/utils/FormatUtil.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/templates/orders-list.mustache

List로 감싸서 받는 DTO인 경우 위 사진처럼 리스트를 지정해줘야 mustache에서 찾을 수 있다.
orderMenus도 Order로 다 받으려고 하니까 LazyLoading 관련 문제가 있었다. 그래서 OrderMenu도 추가하는 DTO수정을 했다.

feat: order-history (+redesign, +format, +filter)

---

src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/resources/static/js/scripts.js
src/main/resources/templates/layout/header.mustache
src/main/resources/templates/layout/sidebar.mustache
src/main/resources/templates/menus-detail-form.mustache

- 메뉴 상세보기 수정, 삭제, 저장, 취소 버튼
- 로그아웃

design: 메뉴 상세보기 버튼, feat: 로그아웃

---

src/main/resources/templates/menus-create-form.mustache
src/main/resources/templates/orders.mustache
src/main/resources/templates/store-update-form.mustache

- 매장 수정하기 데이터 받기
- 2번매장으로 로그인했는데 주문받은 것을 업데이트하다보니 1번매장으로 돌아가는 것을 확인.
- url에 임시로 1로 매핑되어있는 것들 sessionStore.id로 변경

fix: 매장 수정하기 데이터 받기 (fix: /1 -> sessionStore.id 변경)

---

src/main/java/shop/project/pathorderserver/store/Store.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreRequest.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/templates/store-update-form.mustache
src/main/resources/templates/store.mustache

- 매장정보 수정하기
- 사진 기능은 아직. 추후에 한번에 할 것

feat: 매장정보 수정하기 (todo: 사진 업로드)

---

src/main/java/shop/project/pathorderserver/_core/errors/SSRExceptionHandler.java

- fix: 세션 없을 때 에러페이지 대신 로그인폼으로 이동

fix: 로그인 예외 처리 = 401 -> 로그인 창 

---

src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/store/StoreRequest.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/resources/static/js/scripts.js
src/main/resources/templates/menus-detail-form.mustache

feat: menuUpdate (todo: to fix isRequired false)

---

src/main/resources/static/js/scripts.js
src/main/resources/templates/menus-detail-form.mustache

design: menuUpdate +imgUpload +add/del-opt-btn

---

src/main/java/shop/project/pathorderserver/order/Order.java
src/main/java/shop/project/pathorderserver/order/OrderMenu.java
src/main/java/shop/project/pathorderserver/user/UserRequest.java
src/main/java/shop/project/pathorderserver/user/UserResponse.java
src/main/java/shop/project/pathorderserver/user/UserService.java
src/main/resources/static/js/scripts.js
src/main/resources/templates/menus-detail-form.mustache
src/main/resources/templates/menus.mustache

hotfix: 주문하기(총액계산)

---

src/main/java/shop/project/pathorderserver/_core/config/WebMvcConfig.java

fix: 인터셉터 수정

---

src/main/java/shop/project/pathorderserver/store/Store.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/resources/static/js/joinForm.js
src/main/resources/static/js/terms.js
src/main/resources/templates/login-form.mustache

input에 latitude, longitude 숨겨놓았다.
```
... 생략
<div class="form-group form-floating m-3 mx-auto">
<input type="text" name="address" class="form-control" id="storeAddress" value="부산광역시" required>
<label for="storeAddress">주소</label>
<div class="post-code d-flex justify-content-start">
<input type="text" class="form-control" id="postcode" placeholder="우편번호"/>
<input type="button" class="search-btn btn btn-outline-primary" onclick="execDaumPostcode()" value="우편번호 찾기"/>
</div>
<div class="address">
<div class="d-flex justify-content-start">
<input type="text" class="form-control" id="roadAddress" placeholder="도로명주소"/>
<input type="text" class="form-control" id="detailAddress" placeholder="상세주소"/>
</div>
<div>
<input type="text" class="form-control" id="jibunAddress" placeholder="지번주소"/>
<span …
```

feat: 매장 회원가입 시 경도, 위도 받기

---

src/main/java/shop/project/pathorderserver/like/LikeController.java
src/main/java/shop/project/pathorderserver/like/LikeResponse.java
src/main/java/shop/project/pathorderserver/like/LikeService.java

rename: 좋아요 추가 DTO

---

src/main/java/shop/project/pathorderserver/like/LikeRepository.java
src/main/java/shop/project/pathorderserver/like/LikeResponse.java
src/main/java/shop/project/pathorderserver/like/LikeService.java
src/main/java/shop/project/pathorderserver/store/StoreService.java

어제 신청했던 것 같은데
머지하셨던 것 같은데
반영되어있지 않아서 
다시 보냅니당

feat: 좋아요 리스트

---

src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/resources/static/js/orderList.js
src/main/resources/templates/order-list.mustache

feat: 주문 히스토리 상세보기

---

src/main/java/shop/project/pathorderserver/_core/utils/DistanceUtil.java
src/main/java/shop/project/pathorderserver/like/LikeResponse.java
src/main/java/shop/project/pathorderserver/like/LikeService.java
src/main/java/shop/project/pathorderserver/store/StoreController.java
src/main/java/shop/project/pathorderserver/store/StoreResponse.java
src/main/java/shop/project/pathorderserver/store/StoreService.java
src/main/java/shop/project/pathorderserver/user/SessionUser.java
src/main/java/shop/project/pathorderserver/user/UserRequest.java

⚒️ 수정사항: 가게 목록보기 가까운 거리순으로 정렬, distance를 String으로 반환하던 것 int로 변경
거리 계산하는 유틸이 필요함.
두 지점의 위도와 경도를 입력받아, 구면 삼각법(Haversine 공식)을 적용하여 두 지점 사이의 거리를 계산하고, 그 거리를 미터 단위로 반환함.
```
private static final double EARTH_RADIUS_KM = 6371.0;
public static int calculateDistance(double lat1, double lon1, double lat2, double lon2) {
double dLat = Math.toRadians(lat2 - lat1);
double dLon = Math.toRadians(lon2 - lon1);
double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
+ Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
* Math.sin(dLon / 2) * Math.sin(dLon / 2);
double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
double distanceInKm = EARTH_RADIUS_KM * c;
double distanceInMeters = distanceInKm * 1000;
return (int) Math.round(distanceInMeters); // 미터로 변환 후 반올림
}
```
```
public …
```

feat: 거리 계산(매장 목록, 디테일, 좋아요 리스트)

---

src/main/java/shop/project/pathorderserver/like/LikeService.java
src/main/java/shop/project/pathorderserver/user/User.java

통합 테스트 중 내가 좋아요 하지 않은 것도 취소가 되는 것을 발견해서 수정함
```
@Transactional
public void removeLike(LikeRequest.RemoveLikeDTO reqDTO) {
Optional<Like> like = likeRepository.findByCustomerIdAndStoreId(reqDTO.getUserId(), reqDTO.getStoreId());
if (like.isPresent()) {
likeRepository.delete(like.get());
} else {
throw new Exception404("해당 좋아요가 존재하지 않습니다.");
}
}
```

fix: 좋아요 한 리스트에서만 취소할 수 있게

---

src/main/java/shop/project/pathorderserver/menu/Menu.java
src/test/java/shop/project/pathorderserver/store/StoreOwnerControllerTest.java
src/test/java/shop/project/pathorderserver/store/StoreServiceTest.java
src/test/java/shop/project/pathorderserver/user/UserServiceTest.java

fix: jUnit integration test pass

---

src/docs/asciidoc/api.adoc
src/main/java/shop/project/pathorderserver/_core/errors/AppRequest.java
src/main/java/shop/project/pathorderserver/_core/errors/AppValidationHandler.java
src/main/java/shop/project/pathorderserver/_core/errors/WebRequest.java
src/main/java/shop/project/pathorderserver/_core/errors/WebValidationHandler.java
src/main/java/shop/project/pathorderserver/review/ReviewController.java
src/main/java/shop/project/pathorderserver/store/Store.java
src/main/java/shop/project/pathorderserver/store/StoreOwnerController.java
src/main/java/shop/project/pathorderserver/user/User.java
src/main/java/shop/project/pathorderserver/user/UserController.java
src/main/java/shop/project/pathorderserver/user/UserRequest.java
src/main/resources/static/docs/api.html
src/test/java/shop/project/pathorderserver/like/LikeControllerTest.java
src/test/java/shop/project/pathorderserver/review/ReviewControllerTest.java
src/test/java/shop/project/pathorderserver/store/StoreControllerTest.java
src/test/java/shop/project/pathorderserver/store/StoreOwnerControllerTest.java
src/test/java/shop/project/pathorderserver/user/UserControllerTest.java

- 통합테스트 통과
- api 문서 작성 완료 (배포 준비 완료)

docs: asciiDoc (test: integration done) [ready to deploy]
